# Generated by Django 5.0.4 on 2024-05-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('nickname', models.CharField(max_length=10, verbose_name='닉네임')),
                ('content', models.TextField(verbose_name='내용')),
                ('time', models.TimeField(verbose_name='작성 시간')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('dislikes', models.IntegerField(default=0, verbose_name='싫어요수')),
            ],
        ),
    ]
